export const books=[{
    name: "Fomius five", 
    image: "https://www.bing.com/th?id=OIP.veA09rKHRsrnkl495JMfxQHaLB&w=204&h=305&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 50, 
    countInStock: 25, 
    rating:4, 
    numReviews:5, 
},
{
    name: "The Gatesy", 
    image: "https://www.bing.com/th?id=OIP.tMJZlG_-QgWpBb7ehW7HAQHaLG&w=204&h=305&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 60, 
    countInStock: 5, 
    rating:4, 
    numReviews:5, 
},
{
    name: "Hobbit", 
    image: "https://www.bing.com/th?id=OIP.8TD_d_dRAQZ9nMWBjjB8pwHaLe&w=200&h=311&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 50, 
    countInStock: 2, 
    rating:4, 
    numReviews:5, 
},{
    name: "Fomius five", 
    image: "https://www.bing.com/th?id=OIP.veA09rKHRsrnkl495JMfxQHaLB&w=204&h=305&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 50, 
    countInStock: 25, 
    rating:4, 
    numReviews:5, 
},
{
    name: "The Gatesy", 
    image: "https://www.bing.com/th?id=OIP.tMJZlG_-QgWpBb7ehW7HAQHaLG&w=204&h=305&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 60, 
    countInStock: 5, 
    rating:4, 
    numReviews:5, 
},
{
    name: "Hobbit", 
    image: "https://www.bing.com/th?id=OIP.8TD_d_dRAQZ9nMWBjjB8pwHaLe&w=200&h=311&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2",
    author: "dfdsf", 
    category:"dsfds",
    description: "dfsdfsd",
    price: 50, 
    countInStock: 2, 
    rating:4, 
    numReviews:5, 
}]